disabled_rules:
  - trailing_whitespace
  - line_length
  
opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional
  - prefer_zero_over_explicit_init
  
excluded:
  - .build
  - DerivedData
  
line_length:
  warning: 120
  error: 200
  
type_body_length:
  warning: 300
  error: 400
  
file_length:
  warning: 500
  error: 1200
  
function_body_length:
  warning: 40
  error: 100
  
cyclomatic_complexity:
  warning: 10
  error: 20