name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Build
      run: |
        xcodebuild build \
          -project Inro.xcodeproj \
          -scheme Inro \
          -destination 'platform=iOS Simulator,name=iPhone 15'
          
    - name: Run Tests
      run: |
        swift test
        
    - name: SwiftLint
      run: |
        if which swiftlint >/dev/null; then
          swiftlint
        else
          echo "SwiftLint not installed, skipping..."
        fi